# Generated by Django 4.2.1 on 2023-05-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_variation"),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="variation",
            field=models.ManyToManyField(blank=True, null=True, to="store.variation"),
        ),
    ]
