# Generated by Django 4.2.1 on 2023-05-24 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0004_cartitems_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitems",
            name="cart",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="carts.cart"
            ),
        ),
    ]
