# Generated by Django 4.1.7 on 2023-03-11 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50, unique=True)),
                ("slug", models.CharField(max_length=200, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "cat_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="photos/categories"
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
