# Generated by Django 4.2.1 on 2023-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_variation"),
        ("orders", "0003_alter_orderproduct_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
